name: Schedule Scraping

on:
  schedule:
    - cron: '30 10 * * *'  # 毎日19:30（UTC 10:30）に実行

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        run: npm run dev
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/last_content.txt
          git commit -m "Update content" || exit 0
          git push 