name: Schedule Scraping

on:
  #schedule:
  #  - cron: '0 1 * * *'   # 毎日10:00 JST (01:00 UTC)に実行
  #  - cron: '0 6 * * *'   # 毎日15:00 JST (06:00 UTC)に実行
  #  - cron: '30 10 * * *' # 毎日19:30 JST (10:30 UTC)に実行
  workflow_dispatch:  # 手動実行を可能にする

permissions:
  contents: write  # リポジトリへの書き込み権限を明示的に設定

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # トークンを明示的に指定
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright browsers
        run: npx playwright install chromium
        
      - name: Run scraper
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: npm run dev
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/last_content.txt
          git commit -m "Update content" || exit 0
          git push origin main 
